feat: expose `ProfitSharePasses`
sanctuarycomputer/stacks pull request #32
Opened 2024-03-20 21:12 UTC by josephineweidner

This is part of [this task](https://www.notion.so/garden3d/Update-the-Profit-Share-Calculator-to-pull-from-Stacks-be-garden3d-Branded-39505210c9e74674970723a64eac8595). The TLDR is that we want to update https://profit.sanctuary.computer/ to pull from real data in stacks. This PR scaffolds an endpoint to surface that data. 

You can pull down this branch and hit this at `http://localhost:3000/api/profit_share_passes`: 

<details>
<summary>Response</summary>

```
[
  {
    "id": 2,
    "created_at": "2020-01-01T00:00:00.000Z",
    "updated_at": "2021-11-30T20:46:33.430Z",
    "payroll_buffer_months": "1.5",
    "efficiency_cap": "1.6",
    "snapshot": {
      "inputs": {
        "actuals": {
          "gross_payroll": 1974151.47,
          "gross_revenue": 2776966.19,
          "gross_benefits": 0,
          "gross_expenses": 241859.05,
          "gross_subcontractors": 0
        },
        "pre_spent": 0,
        "fica_tax_rate": 0.0765,
        "efficiency_cap": 1.6,
        "total_psu_issued": 427,
        "desired_buffer_months": 1,
        "internals_budget_multiplier": 0.3,
        "projected_monthly_cost_of_doing_business": 221934.96
      },
      "finalized_at": "2020-12-15T00:00:00.000+00:00"
    },
    "internals_budget_multiplier": "0.5",
    "total_psu_issued": 430
  },
  {
    "id": 3,
    "created_at": "2019-01-01T00:00:00.000Z",
    "updated_at": "2021-11-30T20:46:33.436Z",
    "payroll_buffer_months": "1.5",
    "efficiency_cap": "1.6",
    "snapshot": {
      "inputs": {
        "actuals": {
          "gross_payroll": 1010991.09,
          "gross_revenue": 1776824.28,
          "gross_benefits": 0,
          "gross_expenses": 324060.21,
          "gross_subcontractors": 0
        },
        "pre_spent": 0,
        "fica_tax_rate": 0.0765,
        "efficiency_cap": 1.75,
        "total_psu_issued": 250,
        "desired_buffer_months": 1,
        "internals_budget_multiplier": 0.5,
        "projected_monthly_cost_of_doing_business": 111701.16
      },
      "finalized_at": "2019-12-15T00:00:00.000+00:00"
    },
    "internals_budget_multiplier": "0.5",
    "total_psu_issued": 249
  },
  {
    "id": 4,
    "created_at": "2018-01-01T00:00:00.000Z",
    "updated_at": "2021-11-30T20:46:33.443Z",
    "payroll_buffer_months": "1.5",
    "efficiency_cap": "1.6",
    "snapshot": {
      "inputs": {
        "actuals": {
          "gross_payroll": 653351,
          "gross_revenue": 1168836,
          "gross_benefits": 0,
          "gross_expenses": 304610,
          "gross_subcontractors": 0
        },
        "pre_spent": 0,
        "fica_tax_rate": 0,
        "efficiency_cap": 1.6,
        "total_psu_issued": 139,
        "desired_buffer_months": 1,
        "internals_budget_multiplier": 0.5,
        "projected_monthly_cost_of_doing_business": 84000
      },
      "finalized_at": "2018-12-15T00:00:00.000+00:00"
    },
    "internals_budget_multiplier": "0.5",
    "total_psu_issued": 128
  },
  {
    "id": 5,
    "created_at": "2017-01-01T00:00:00.000Z",
    "updated_at": "2021-11-30T20:46:33.449Z",
    "payroll_buffer_months": "1.5",
    "efficiency_cap": "1.6",
    "snapshot": {
      "inputs": {
        "actuals": {
          "gross_payroll": 346502.51,
          "gross_revenue": 614008.84,
          "gross_benefits": 0,
          "gross_expenses": 132485.05,
          "gross_subcontractors": 0
        },
        "pre_spent": 0,
        "fica_tax_rate": 0,
        "efficiency_cap": 1.9,
        "total_psu_issued": 84,
        "desired_buffer_months": 1,
        "internals_budget_multiplier": 0.5,
        "projected_monthly_cost_of_doing_business": 28750
      },
      "finalized_at": "2017-12-15T00:00:00.000+00:00"
    },
    "internals_budget_multiplier": "0.5",
    "total_psu_issued": 54
  },
  {
    "id": 1,
    "created_at": "2021-11-30T20:46:33.424Z",
    "updated_at": "2021-12-21T19:42:27.554Z",
    "payroll_buffer_months": "1.0",
    "efficiency_cap": "1.6",
    "snapshot": {
      "inputs": {
        "actuals": {
          "gross_payroll": "1872023.81",
          "gross_revenue": "4027231.33",
          "gross_benefits": "276168.33",
          "gross_expenses": "324414.78",
          "gross_subcontractors": "592284.77"
        },
        "pre_spent": "29122.11",
        "fica_tax_rate": 0.0765,
        "efficiency_cap": "1.6",
        "total_psu_issued": "606.2",
        "desired_buffer_months": "1.0",
        "internals_budget_multiplier": "0.3",
        "projected_monthly_cost_of_doing_business": "318923.51"
      },
      "finalized_at": "2021-12-21T19:42:27.554+00:00"
    },
    "internals_budget_multiplier": "0.3",
    "total_psu_issued": 597
  },
  {
    "id": 6,
    "created_at": "2022-01-01T00:00:37.813Z",
    "updated_at": "2022-12-15T20:20:31.873Z",
    "payroll_buffer_months": "1.75",
    "efficiency_cap": "1.69",
    "snapshot": {
      "inputs": {
        "actuals": {
          "gross_payroll": "2338143.13",
          "gross_revenue": "6072778.68",
          "gross_benefits": "329431.75",
          "gross_expenses": "428162.45",
          "gross_subcontractors": "1151517.51"
        },
        "pre_spent": "26282.61",
        "fica_tax_rate": 0.0765,
        "efficiency_cap": "1.69",
        "total_psu_issued": "720.75",
        "desired_buffer_months": "1.75",
        "internals_budget_multiplier": "0.7",
        "projected_monthly_cost_of_doing_business": "351184.05"
      },
      "finalized_at": "2022-12-15T20:20:31.872+00:00"
    },
    "internals_budget_multiplier": "0.7",
    "total_psu_issued": 718
  },
  {
    "id": 7,
    "created_at": "2023-01-02T15:04:13.123Z",
    "updated_at": "2023-12-15T20:26:20.245Z",
    "payroll_buffer_months": "1.5",
    "efficiency_cap": "1.8",
    "snapshot": {
      "inputs": {
        "actuals": {
          "gross_payroll": "2416423.16",
          "gross_revenue": "6189796.82",
          "gross_benefits": "338022.69",
          "gross_expenses": "762310.51",
          "gross_subcontractors": "1448610.12"
        },
        "pre_spent": "19936.54",
        "fica_tax_rate": 0.0765,
        "efficiency_cap": "1.8",
        "total_psu_issued": "930.57",
        "desired_buffer_months": "1.5",
        "pre_spent_reinvestment": 717606.3729008734,
        "internals_budget_multiplier": "1.35",
        "projected_monthly_cost_of_doing_business": "364717.69"
      },
      "finalized_at": "2023-12-15T20:26:20.245+00:00"
    },
    "internals_budget_multiplier": "1.35",
    "total_psu_issued": 931
  },
  {
    "id": 8,
    "created_at": "2024-01-01T01:42:55.539Z",
    "updated_at": "2024-01-01T01:42:55.539Z",
    "payroll_buffer_months": "1.5",
    "efficiency_cap": "1.6",
    "snapshot": null,
    "internals_budget_multiplier": "0.5",
    "total_psu_issued": 1136
  }
]
```

</details>

2024-03-20 21:19 UTC, josephineweidner commented on app/controllers/api/profit_share_passes_controller.rb
> +    result = profit_share_passes.map{|p| p.as_json.merge({"total_psu_issued"=> p.total_psu_issued}) }
Maybe this is a rails anti-pattern, since we're adding something to the response here that isn't part of the base `ProfitSharePass`? LMK your thoughts, just wanted to get something working first. 

Also thought about adding a `total_psu_issued` column to the `profit_share_passes` instead of calculating it each time, but I'm not totally convinced that extra work is necessary (though it could be a good opportunity for me to run some migrations in rails land).

2024-03-20 21:47 UTC, josephineweidner commented on app/controllers/api/profit_share_passes_controller.rb
> +    result = profit_share_passes.map{|p| p.as_json.merge({"total_psu_issued"=> p.total_psu_issued}) }
It does! Thank you!

2024-03-21 19:01 UTC, hhff commented on app/controllers/api/profit_share_passes_controller.rb
> +    render json: result, each_serializer: Api::ProfitSharePassSerializer
i do believe we're going to need to send some CORS headers down if we want the browser to allow this request

2024-03-22 15:07 UTC, josephineweidner commented
FYI I'm probs gonna change this to use JSONAPI::Serializer now that I know a little more about ember so that's why I haven't merged it in (in addition to the dependency stuff which I'll resolve after https://github.com/sanctuarycomputer/stacks/pull/33 is merged) @joshmcclain

2024-03-25 13:03 UTC, hhff commented
> FYI I'm probs gonna change this to use JSONAPI::Serializer now that I know a little more about embe

@josephineweidner -- a widely misunderstood thing about ember is that you need to use their serializer / deserializer / ember-data store to get API data into the frontend.

You can simply make a fetch request from the route.js file instead:
https://github.com/ember-cli/ember-fetch

I'd highly recommend this approach over adding the clunky / heavy duty machinery that is JSONAPI::Serializer to rails, etc etc

2024-03-26 18:39 UTC, hhff requested changes

2024-03-26 18:39 UTC, hhff commented on app/models/profit_share_pass.rb
> +  end
A few notes here:
- There's inconsistency in the naming convention of these methods, some end with `_from_snapshot` and some don't
- we shouldn't fallback to `nil`, rather a type that corresponds to the type returned in a good case (so the FE doesn't need to do nil checks (this is more of a sanctuary best practice that ruby dogma)
- a good way to dig through hashes with string keys in Ruby is using `dig`, for example: `snapshot.dig("inputs", "fica_tax_rate") || 0`
- a good way to wrap a chained method in a nil check is to use `try`, for example: `snapshot.try(:dig, ["inputs", "fica_tax_rate"]) || 0`
- that said, Ruby's unsafe access operator probably beats `try` because wrapping a chained method feels unergonomic, for example: `snapshot&.dig("inputs", "fica_tax_rate") || 0`
- finally, logic used **soley** for rendering a model should be in the serializer file, not the model file (your serializer methods can do the above digging directly, rather than calling a model method)!

2024-03-26 18:39 UTC, hhff commented on config/initializers/cors.rb
> +      origins 'http://localhost:4200'
Let's make this `origins '*'`, I'd like this data to be publicly accessible to all websites

2024-03-27 16:15 UTC, josephineweidner commented on app/models/profit_share_pass.rb
> +  end
Sorry @hhff - this code wasn't ready for re-review, I was like "just make it work" mode after hooking it up to the ember side. Your notes are v helpful nonetheless and I'll be sure to address them! 

Marking this PR as draft until it's actually ready for your eyes again. Thanks!

2024-03-27 18:57 UTC, josephineweidner commented on config/initializers/cors.rb
> +      origins 'http://localhost:4200'
Done, but limited it so that only `profit_share_passes` can be accessed. Sound good?

2024-03-27 19:00 UTC, josephineweidner commented on app/models/profit_share_pass.rb
> +  end
Re fallback vals: `to_f` takes care of this for us (which we need to do anyway bc some snapshots start storing values as strings instead of floats). Not as explicit as `|| 0` but it works and I think `.to_f` _and_ a fallback would be misleading about `to_f` behavior. I can add a comment if this isn't obvious to Ruby devs?

```
irb(main):001:0>  nil.to_f
=> 0.0
```

2024-03-27 19:24 UTC, hhff requested changes
nitpicks~!

2024-03-27 19:24 UTC, hhff commented on app/serializers/api/profit_share_pass_serializer.rb
> +  end
while you're filtering for `ProfitSharePass.where.not(snapshot: nil)` in the controller, it's entirely possible for a future developer to pass a `ProfitSharePass.where(snapshot: nil)` to this serializer in a different controller action. So I'd recommend still using the safe access operator to test that `snapshot` is not nil.

The serializer should to expect/rely on something upstream prepared a specific subset of model variations for it to render

2024-03-27 19:24 UTC, hhff commented on app/models/profit_share_pass.rb
> +  end
Why is these new LOC here? Didn't we already have a method like this?

2024-03-27 19:55 UTC, josephineweidner commented on app/serializers/api/profit_share_pass_serializer.rb
> +  end
Oh I see what you mean. Sorry I misunderstood you above. 

```
irb(main):005:0> p = ProfitSharePass.order(:created_at).last
  ProfitSharePass Load (0.9ms)  SELECT "profit_share_passes".* FROM "profit_share_passes" ORDER BY "profit_share_passes"."created_at" DESC LIMIT $1  [["LIMIT", 1]]
=> #<ProfitSharePass id: 8, created_at: "2024-01-01 01:42:55", updated_at: "2024-01-01 01:42:55", payroll_buf...
irb(main):006:0> p.snapshot.dig("inputs", "desired_buffer_months").to_f
Traceback (most recent call last):
        1: from (irb):6
NoMethodError (undefined method `dig' for nil:NilClass)
irb(main):007:0> p.snapshot&.dig("inputs", "desired_buffer_months").to_f
=> 0.0
```

Yes, agreed this is a problem! Fixed in latest commit

2024-03-27 20:16 UTC, josephineweidner commented on app/models/profit_share_pass.rb
> +  end
A similar call is made [here](https://github.com/sanctuarycomputer/stacks/blob/c45533c0fac7dcc26f256e4cb5fb188e9af5e71c/app/models/profit_share_pass.rb#L153) in `make_scenario`, although there we want to calculate based on projected_psu_by_eoy instead of psu_earned_by(finalization_day)

Consolidated in https://github.com/sanctuarycomputer/stacks/pull/32/commits/8761a35068f49e7e029b868619390f56b98f6a5d - lmk what you think

2024-03-27 20:18 UTC, hhff approved these changes

2024-04-05 16:05 UTC, merged